name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Create secret.js
        run: touch secret.js

      - name: Inject Secret ID
        run: echo "export const SS_ID = '${{ secrets.SS_ID }}';" > secret.js

